apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: acmecorp-ingress
  namespace: ecommerce
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
    - host: acmecorp.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: checkout-frontend
                port:
                  number: 3000
          - path: /api/payments
            pathType: Prefix
            backend:
              service:
                name: payments-api
                port:
                  number: 4001
          - path: /api/inventory
            pathType: Prefix
            backend:
              service:
                name: inventory-service
                port:
                  number: 4002
